### ISSUE TITLE
Can you add a web.config?

### ISSUE THREAD

**Issue by aarongustafson** [stowball/color-flashcards#2]
Here's a template: https://a-k-apart.com/webconfigs/web.config.node.txt

**Comment by stowball** [comment]
Sorry, didn't realise that. I never read that sentence as it began with "If you are using PHP, make sure your index file is named index.php." so just skipped over it XD

Can you just point to the `docs/` folder instead and use it as a static site? It's all committed

**Comment by aarongustafson** [comment]
I can try.

**Comment by aarongustafson** [comment]
Deployed. I have a new issue for you though…
